### ISSUE TITLE
Bug: Use TRAVIS_REPO_SLUG not TRAVIS_SLUG

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic-tsunami/beaver#10]
**TRAVIS_SLUG** doesn't exist as a travis environment variable. 
From the [travis documentation](https://docs.travis-ci.com/user/environment-variables/) it seems like **TRAVIS_REPO_SLUG** is the most appropriate to use in **beaver**

**Comment by leandro-lucarella-sociomantic** [comment]
Woops!
