### ISSUE TITLE
Add more automation to Dockerfile generation

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/beaver#13]
What do you think about auto-generating Dockerfile by beaver completely? (while still keeping separate `docker/build` script for repo specific preparations). Amount of duplicated stuff there starts to pile up when you look at https://github.com/sociomantic-tsunami/ocean/pull/192

Would be cool to just do this:

```
install:
    - beaver generate --base "sociomantictsunami/dlang:trusty-v2" --script "docker/build"
```

**Comment by leandro-lucarella-sociomantic** [comment]
I think the amount of stuff in the Dockerfiles are still small and they shouldn't change often, so for now I would keep the approach of having Dockerfiles that are as similar to the real thing as possible.

`docker build` finally got the ability to generate images from STDIN, which will ease with the generated Dockerfiles, so I think in a near future we could go for that. I don't like it very much that it makes is harder to just clone a project and build it by just creating a docker image using regular docker commands.

But I don't know, maybe at some point we can add some beaver-makd integration to avoid the boilerplate for the developer and maybe have a `make build-image` or something.

**Comment by leandro-lucarella-sociomantic** [comment]
We will need to keep a Dockerfile for sure, projects need to be able to define labels and do other sort o things, but we could keep it just with the base `FROM` image. Maybe it can be called `Dockerfile.include` or something to make it clear that it is not a full Dockerile.

**Comment by mihails-strasuns-sociomantic** [comment]
How `make build-image` is any better than `beaver generate` in that sense? If you clone project, beaver submodule which provides shell script will be there too.

My main concern is about things like `ENV` and `ARG` we are starting to add (you even made a typo yourself adjusting only one of two dockerfiles when last updating my PR)

**Comment by leandro-lucarella-sociomantic** [comment]
> How make build-image is any better than beaver generate in that sense? If you clone project, beaver submodule which provides shell script will be there too.

I meant `make build-image` would be just calling to `beaver generate`, but beaver is not in the `PATH` normally, so it would just be to avoid extra work for the developers (so they don't have to call `submodules/beaver/bin/beaver generate`.

> My main concern is about things like ENV and ARG we are starting to add (you even made a typo yourself adjusting only one of two dockerfiles when last updating my PR)

Yes, I understand that. We are talking about the same (except that you propose no `Dockerfile` at all and I say we need at least one `Dockerfile` partial inclusion for potential customization.

**Comment by leandro-lucarella-sociomantic** [comment]
What I want to prioritize is to be able to run stuff in a docker image defined by the project. Having the docker image is very useful not only for testing but for local development (since I usually don't work on a particular project but rather jump from project to project, I don't want to install every single dependency of every project just to work with it for 2 hours), so I use this a lot. This is why I mentioned makd integration.

**Comment by leandro-lucarella-sociomantic** [comment]
https://github.com/sociomantic-tsunami/beaver/pull/20
