### ISSUE TITLE
`dlang codecov` doesn't produce code coverage reports

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/beaver#35]
Although projects run `make codecov` (https://github.com/sociomantic-tsunami/ocean/blob/e1eecc4d3621cb502f8bc265f00da49be9e2ef54/.travis.yml#L38) they don't produce any coverage reports to run, as `beaver dlang make` doesn't pass `-cov` to the `DFLAGS`: https://github.com/sociomantic-tsunami/beaver/blob/v0.x.x/bin/dlang/make

**Comment by leandro-lucarella-sociomantic** [comment]
What this does is just running make, so make should be doing the args passing.

As @mihails-strasuns-sociomantic said, the problem probably is that ocean's makefile relies on the `CI` env variable to be set, but it's not being forwarded.

https://github.com/sociomantic-tsunami/ocean/blob/e1eecc4d3621cb502f8bc265f00da49be9e2ef54/Build.mak#L11-L13

To fix this more generally, we need to fix #25. As a workaround we can add `BEAVER_EXPORTED_VARS=CI` to ocean's `.travis.yml`.

**Comment by mihails-strasuns-sociomantic** [comment]
```
query: branch=v3.x.x&commit=478a077c38bf95916d93dce2da00209a7c71370f&build=1560.7&build_url=&name=unittest&tag=&slug=sociomantic-tsunami%2Focean&service=travis&flags=devel,xenial,dmd_2_071_2_s*,unittest&pr=383&job=308950297
    -> Pinging Codecov
HTTP 400
flags must match pattern ^[\w\,]+$
```

**Comment by mihails-strasuns-sociomantic** [comment]
So it does need both CI present and fix in beaver for flag format https://github.com/sociomantic-tsunami/ocean/pull/383

**Comment by leandro-lucarella-sociomantic** [comment]
I'm not following...

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic you implemented beaver command for code coverage to also submit bunch of tags - codecov service rejects submission because of them, reporting invalid regex

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, I see, it's the new `*` in the version of DMD I guess. We need to sanitize the input :roll_eyes:

**Comment by leandro-lucarella-sociomantic** [comment]
https://github.com/sociomantic-tsunami/beaver/issues/36

**Comment by leandro-lucarella-sociomantic** [comment]
There was some partial sanitization but `*` was not excluded, now I'm cleaning `\W` and for all flags, so it should be future proof.

**Comment by leandro-lucarella-sociomantic** [comment]
> #36

Oh, I thought this was an ocean issue :grin:
