### ISSUE TITLE
Codecov: return code and "beaver codecov" cmd

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic-tsunami/beaver#47]
#### `beaver codecov` requires coverage has already been captured with gcov

When using `beaver codecov` to run codecov inside a docker container it assumes that the gcov has already been run, `beaver-codecov`

https://github.com/sociomantic-tsunami/beaver/blob/61aebb1e7984c02c9b170a4a3040334fee824a2c/bin/dlang/codecov#L18

and the codecov script is executed with `gcov` disabled: 

https://github.com/sociomantic-tsunami/beaver/blob/61aebb1e7984c02c9b170a4a3040334fee824a2c/bin/dlang/codecov#L53

IIUC this is due to how the coverage generation is integrated with MakD. However with projects not using MakD and testing with different compilers, the generation of coverage is dependent on the tools provided by the specific compiler and it's toolset. 

You can still use the codecov script provided by beaver with the requirements described above, but only when using it directly as `bin/codecov-bash`. Thus the advantage of using beaver for coverage isn't that big. 

#### Return code passing -Z arg to codecov 

Does the documentation for `-Z` still apply when codecov is invoked through beaver? 

`    -Z           Exit with 1 if not successful. Default will Exit with 0`

**Comment by leandro-lucarella-sociomantic** [comment]
About the first issue, I don't get it. Why is that a problem? You run your program, you generate your coverage reports, then you upload them.

About the second issue, if that is a question, can you try it by yourself? It think it should be carried. If it is a real issue, please create a separate issue :)

**Comment by andreas-bok-sociomantic** [comment]
> About the first issue, I don't get it. Why is that a problem? You run your program, you generate your coverage reports, then you upload them.

It is a lot easier to let the `codecov-bash` script generate the coverage report when the project supports coverage for different compilers and versions. 

> About the second issue, if that is a question, can you try it by yourself? It think it should be carried. If it is a real issue, please create a separate issue :)

I will try it out

**Comment by leandro-lucarella-sociomantic** [comment]
I don't get it, you just mean discovering the coverage reports that are out there?

**Comment by leandro-lucarella-sociomantic** [comment]
`beaver codecov` is just a wrapper for `codecov-bash`...

**Comment by andreas-bok-sociomantic** [comment]
> I don't get it, you just mean discovering the coverage reports that are out there?

No, generating the report from the `.gcda`. 

> beaver codecov is just a wrapper for codecov-bash...

Yes, but it disables `gcov` by default with the `-X gcov`  cli option

**Comment by leandro-lucarella-sociomantic** [comment]
> No, generating the report from the .gcda.

Mmm, ok, I didn't know it generated anything like that.

> Yes, but it disables gcov by default with the -X gcov cli option

OK, this is a bug, that should be only enabled in `dlang codecov`.

**Comment by andreas-bok-sociomantic** [comment]
> Mmm, ok, I didn't know it generated anything like that.

It does. And more importantly it can create the report from the coverage files generated different compilers. 
Before I had to generate a wrapper shell script to support clang code coverage report generation.

**Comment by leandro-lucarella-sociomantic** [comment]
Can you create a more specific issue now? This one got too complicated and it's hard to see exactly what needs to be done/fixed.

**Comment by andreas-bok-sociomantic** [comment]
Yes

**Comment by leandro-lucarella-sociomantic** [comment]
Closing while waiting for the new issue :)
