### ISSUE TITLE
Allow passing beaver options via CLI

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/beaver#53]
So far most options for beaver commands are passed via environment variables, but in more complex scripts it is sometimes useful to be able to pass them as CLI options instead, so we should implement a consistent way to do that.

FYI @mihails-strasuns-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
I've been spending some time today trying to address this in a safe and general way, and it is tricky.

My goal is to have a `lib/args.sh` that by just including it (`. lib/args.sh`) it will parse the command-line looking for common options and setting them (to keep it simple my aim is to just convert options to `export BEAVER_<option>=<value>`.

I don't want to have to declare which options are understood by every command because it will soon become too messy and unmaintainable.

I already implemented this to convert options from `--<option> <value>` but I just realized that some commands can and will implement their own options, and even some forward them to other programs (like `docker`), so knowing beforehand which options are safe to parse is not that easy (and just converting any `--<option> <value>` to `export BEAVER_<option>=<value>` is plain wrong).

To fix this I plan to implement a catch-all option like `-e <option>=<value>`, but then, using `-e` (or anything short really) has a huge potential to clash to commands own options, so the only way I see is to use something quite verbose, like `beaver cmd --beaver-opt <option>=<value>`.

Once we come to this, then I wonder if it brings any value over using over using `BEAVER_<option>=<value> beaver cmd`. :thinking: 

Opinions?

**Comment by mihails-strasuns-sociomantic** [comment]
My original idea was to make `args.sh` parse and remove common arguments from `$@` so that any specific command may only parse remaining ones. But I was not able to make it work in bash, especially when it came to storing multi-argument flags :)

I think when we talked about separating beaver and sub-command args last time you have proposed to use `--` for that.

**Comment by leandro-lucarella-sociomantic** [comment]
Actually, thinking about it, since all `beaver` subcommands are dispatched by `bin/beaver`, we can make the place of the arguments count, so `beaver --general-beaver-opts command --command-opts` might solve this in a much more general way. Since `beaver` will only translate those options to env variables, it makes it super general.

**Comment by leandro-lucarella-sociomantic** [comment]
Do you think this is a reasonably usable approach?

**Comment by leandro-lucarella-sociomantic** [comment]
It would be weird that some options will look (and really be) command-specific.

**Comment by leandro-lucarella-sociomantic** [comment]
(the `--` could also work, but we need to change all the public CLI. I will give it some more thought and try things out in the meantime.

**Comment by mihails-strasuns-sociomantic** [comment]
> It would be weird that some options will look (and really be) command-specific.

This would be my main concern indeed

**Comment by leandro-lucarella-sociomantic** [comment]
The `--` seems to be very complicated, since a lot of commands are just wrappers to other commands, I think it gets really tricky to do it properly right now. Also, the problem for me with this approach is, I don't want to build a static set of options to override, I want to map automatically options to env vars, because otherwise it will be a nightmare to maintain (we are centralizing a set of options that now are distributed and defined by subcommands themselves). 

Using automatically mapped options have it own set of problems (probably the worse one is typos will end up in some options being ignored silently, because they will just define an env var that's not used), but still for now right now it seems like the most sensible approach.

**Comment by mihails-strasuns-sociomantic** [comment]
Sounds reasonable.

**Comment by leandro-lucarella-sociomantic** [comment]
OK, https://github.com/sociomantic-tsunami/beaver/pull/55 is out there. I know it still sucks a bit, but doing anything clearer than that (from the users perspective) would imply rewriting most of beaver, so I don't think it is really justified (at least until we are ready to rewrite beaver, but I would rather find a better CI and kill it instead :P).
