### ISSUE TITLE
dlang/d2-release should also switch submodules to use the +d2 tag

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/beaver#56]
If the submodules point to D1 code, then the D2 tag becomes untesteable.

**Comment by leandro-lucarella-sociomantic** [comment]
Doing this after the code is converted and before committing the changes should do the trick:

```sh
git submodule foreach \ 
    'git reset --hard && 
    git fetch origin $(git describe)+d2 && 
    git checkout $(git describe)+d2 || :' 
```

The trailing `|| :` is to avoid this failing, since some submodules (like beaver) are not D code and don't have corresponding `+d2` tags.

**Comment by Geod24** [comment]
Since there's no more D1 code, WONTFIX.
