### ISSUE TITLE
Add automatic conversion of tags to D2

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/beaver#7]
What [Ocean does](https://github.com/sociomantic-tsunami/ocean/pull/100) now should be done by beaver, but also we need to update this to push the tags with a suffix `+d2` (which would mean build metadata for SemVer) to the same repo, not a new one.

**We have to be careful not to do this same process for the automatically converted tags!** (Basically if the original tag ends with `+d2` it should do nothing).

**Comment by mathias-lang-sociomantic** [comment]
Should converted tags be tested before being pushed, for sanity check ?

**Comment by leandro-lucarella-sociomantic** [comment]
> Should converted tags be tested before being pushed, for sanity check ?

Is the other way around. First the testing is done for both D1 and D2, once all was tested, then the converted code should be pushed.

**Comment by leandro-lucarella-sociomantic** [comment]
Done! Will be released in v0.3.0
